require:
   - 'rubocop-rails'

AllCops:
   TargetRubyVersion: 2.7
   Exclude:
      - 'bin/**/*'
      - 'db/**/*'
      - 'spec/spec_helper.rb'
      - 'spec/rails_helper.rb'
      - 'config/puma.rb'
      - 'config/initializers/**/*'
      - 'config/environments/**/*'
      - 'config/application.rb'

Layout/ClosingParenthesisIndentation:
   Enabled: false

Style/Documentation:
   Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Metrics/BlockLength:
   Enabled: false

Style/FrozenStringLiteralComment:
   Enabled: false

Layout/ArgumentAlignment:
   Enabled: false

Style/IfUnlessModifier:
   Enabled: false

Style/GuardClause:
   Enabled: false

Rails/HasManyOrHasOneDependent:
   Enabled: false

Naming/AccessorMethodName:
   Enabled: false

Style/ClassAndModuleChildren:
   Enabled: false

Rails/Date:
   Enabled: false

Rails/InverseOf:
   Enabled: false

Metrics:
   Enabled: false

Rails/UniqueValidationWithoutIndex:
   Enabled: false

Rails/LexicallyScopedActionFilter:
   Enabled: false
