version: '3.3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/td7-projeto-final
    command: bash -c "bin/setup && rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      TZ: Sao_Paulo/Sao_Paulo