version: '3.3'
services:
  web:
    container_name: td7-projeto-final
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/td7-projeto-final
    command: bash -c "bin/setup && rails server -b 0.0.0.0 -p 3000 && bundle exec sidekiq" #ver sobre makefile pra tirar esse bin setup daqui(eu acho)
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      TZ: Sao_Paulo/Sao_Paulo
    depends_on:
      - db
      - redis
    networks:
      - hiring
      - db_network
      - redis_network

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      TZ: Sao_Paulo/Sao_Paulo
    networks:
      - db_network

  redis:
    command: "redis-server"
    container_name: redis
    restart: always
    image: redis
    networks:
      - redis_network

  # jobs:
  #  image: td7-projeto-final_web:latest
  #  command: "bundle exec sidekiq"
  #  networks:
  #    - redis_network
  #  depends_on:
  #    - db
  #    - redis

networks:
  hiring: 
    external: true
  db_network:
    external: false
  redis_network: 
    external: false